### ISSUE TITLE
Leveldb does not show tables/data

### ISSUE THREAD

**Issue by nicolas-raoul** [fastogt/fastonosql#5] opened 2016-06-13 09:07 UTC
I opened a LevelDB folder that contains data for sure.

PROBLEM: No data is shown:

![](http://i.imgur.com/ZhefRWX.png)

I clicked on all buttons/options, nothing show any data.
##

**Comment by topilski** [comment] 2016-06-13 09:58
Good day @nicolas-raoul , is logs contains any errors?

**Comment by nicolas-raoul** [comment] 2016-06-13 10:31
Thank you for the quick reply! As seen in the screenshot above, nothing appear in the Logs tab, even with log enabled and set to level 0 or 10000.

**Comment by topilski** [comment] 2016-06-14 05:31
can't reproduce your bug, can you send your db to my email? atopilski@gmail.com

**Comment by topilski** [comment] 2016-10-03 06:03
Hi @nicolas-raoul , please try to reproduces this issue in new version of FastoNoSQL.

**Comment by topilski** [comment] 2016-11-08 17:29
ping

**Comment by nicolas-raoul** [comment] 2016-11-09 03:23
I am unfortunately unable to test due to #13 and #14, but anyone can test easily by installing Chrome and any Chrome extension.
Thanks! :-)

**Comment by topilski** [comment] 2016-11-19 14:05
Fixed in version 1.1.0 please check behavior and close issue if work as needed.

**Comment by topilski** [comment] 2016-11-28 06:52
ping

**Closed** 2016-11-30 07:40 UTC
Labels: bug
