### ISSUE TITLE
FastNoSQL.exe shuts down immediately

### ISSUE THREAD

**Issue by Trolldemorted** [fastogt/fastonosql#23] opened 2017-03-02 09:54 UTC
`fastonosql.exe` is running for ~1s and silently shuts down on my W10 Pro N 64bit machine.

Happens with both the installed and the portable version.

Could not find any output or logs, unfortunately.

**Comment by topilski** [comment] 2017-03-02 09:58
Hi @Trolldemorted , please check folder C:\Users\${NAME}\ , you can find fastonosql.log

**Comment by Trolldemorted** [comment] 2017-03-02 10:02
nope, file does not exist

**Comment by topilski** [comment] 2017-03-02 10:06
For which database you want to use FastoNoSql? if for redis you can try FastoRedis, may be FastoRedis will work.

**Comment by Trolldemorted** [comment] 2017-03-02 10:14
a chrome app's leveldb, unfortunately i have not yet found a working editor on windows.

**Comment by topilski** [comment] 2017-03-02 10:23
Yes, for leveldb worked only FastoNoSQL, i will try to reproduce and fix this issue, also you can login to fastonosql.com site and try to build own installer, please select only leveldb in options. 
![image](https://cloud.githubusercontent.com/assets/4686379/23503137/6c1a38ae-ff4b-11e6-93d7-914ce67fa480.png)

**Comment by Trolldemorted** [comment] 2017-03-02 13:08
The fresh built installer "worked" as in the UI starts up now.

However, opening the db does not do much:

![stuck](https://cloud.githubusercontent.com/assets/10261186/23508284/3797de96-ff51-11e6-915f-7a930d808d0f.PNG)

log says:
```
14:05:41.235 FastoNoSQL [ERROR] Fail connect to server: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator!
```

I am new to leveldb, i should just open the folder with the *.ldb files, shouldn't i? Note that the db is rather big (~700 MB), can that cause issues?

**Comment by topilski** [comment] 2017-03-02 13:30
Please select folder where placed leveldb files.

**Comment by unforgettableid** [comment] 2017-03-27 01:04
@Trolldemorted: Thanks for your report!

FastoNoSQL is probably crashing silently. So you're probably experiencing two bugs.

A) It crashed silently when it should have shown you a Windows Error Reporting dialog box. This is bug #28.
B) It crashed, even though it shouldn't crash at all. This is the bug you reported.

Please do this:

* Press Win+R to open the "Run" dialog.
* Type: `%LOCALAPPDATA%\CrashDumps`
* Click OK.

A) Are there still any FastoNoSQL crash dump files there, even though they were created so many weeks ago? If so, could you please visit https://github.com/fastogt/fastonosql/issues/23 and then drag and drop them into a comment?

B) If there are no FastoNoSQL crash dump files there, please check in the "View all problem reports" control panel and tell us whether or not there are any FastoNoSQL problem reports there.

**Comment by unforgettableid** [comment] 2017-03-27 01:32
@Trolldemorted:

C)  Please run `msinfo32.exe`. What processor (CPU) do you have?

**Comment by unforgettableid** [comment] 2017-03-27 01:33
@Trolldemorted: If you have a Pentium or Celeron CPU, you might be experiencing bug #29, and if so, we don't need any crash dump files.

**Comment by Trolldemorted** [comment] 2017-03-27 09:14
there is no CrashDumps folder in %LOCALAPPDATA% on my system.

The db in question does not exist any more, but the processor was a phenom II X4 940.

**Comment by unforgettableid** [comment] 2017-03-29 13:19
The Phenom II X4 940 is a 64-bit CPU, but it doesn't have any AVX support. [(Source.)](http://cpuboss.com/cpus/AMD-Phenom-II-X4-940-vs-AMD-FX-4300) If you were running the 64-bit version of FastoNoSQL, you probably experienced bug #29. The workaround is to use the 32-bit version instead.

It would be good if you could please do the following:

A) Open up the "View all problem reports" control panel and tell us whether or not there are any FastoNoSQL problem reports there.
B) If there are, please right-click on a few of them, one at a time.
C) For each one, choose "View technical details". Are an exception code and an exception offset shown? What are the code and the offset?

**Comment by Trolldemorted** [comment] 2017-03-29 13:28
There are a lot, here is one:

```
Quelle
fastonosql

Zusammenfassung
Nicht mehr funktionsfähig

Datum
‎02.‎03.‎2017 11:50

Status
Der Bericht wurde gesendet.

Beschreibung
Pfad der fehlerhaften Anwendung:	C:\Program Files\FastoNoSQL\FastoNoSQL.exe

Problemsignatur
Problemereignisame:	APPCRASH
Anwendungsname:	FastoNoSQL.exe
Anwendungsversion:	1.5.0.0
Anwendungszeitstempel:	01410158
Fehlermodulname:	FastoNoSQL.exe
Fehlermodulversion:	1.5.0.0
Fehlermodulzeitstempel:	01410158
Ausnahmecode:	c000001d
Ausnahmeoffset:	0000000000a57bad
Betriebsystemversion:	10.0.14393.2.0.0.256.49
Gebietsschema-ID:	1031
Zusatzinformation 1:	d986
Zusatzinformation 2:	d98638711348b9469ee746f75705b0e9
Zusatzinformation 3:	52e2
Zusatzinformation 4:	52e23fa37fc61a0b55b905945af9d71e

Weitere Informationen über das Problem
Bucket-ID:	c5df9074b36e56cd12e30831bc15b7b7 (120695870482)
```

Unfortunately, no exception or stacktrace. I have indeed used the 64bit version, but unfortunately i cannot test the 32bit one because the database in question is gone.

**Comment by unforgettableid** [comment] 2017-03-29 14:26
Thanks for all your replies!

I looked at the website of Error Toolkit, Inc.; they (correctly) report that exception code `c000001d` means `STATUS_ILLEGAL_INSTRUCTION`.

Offset `0000000000a57bad` means `FastoNoSQL!unqlite_util_random_num+5f8a4d`.

So it's confirmed now:
* Bug #29 caused FastoNoSQL to crash at startup for you.
* But no crash dialog ever appeared on your screen, because of bug #28.

@topilski: I think we can close this issue now. :)

**Closed** 2017-03-29 14:28 UTC
